class GeminiStub:
    def __init__(self, api_key: str | None = None):
        self.api_key = api_key

    def complete(self, prompt: str) -> str:
        """Generate a response (stub - replace with real Gemini API)."""
        # Return contextual responses based on prompt
        prompt_lower = prompt.lower()

        if "employment" in prompt_lower and "contract" in prompt_lower:
            return """EMPLOYMENT AGREEMENT

This Employment Agreement ("Agreement") is entered into as of the Effective Date, between the Employer and Employee.

1. POSITION AND DUTIES
Employee shall serve as [Position] and shall perform all duties and responsibilities as reasonably assigned.

2. COMPENSATION
Employee shall receive an annual salary of [Salary], payable in accordance with applicable law.

3. BENEFITS
Employee shall be entitled to the following benefits: health insurance, retirement plan, paid time off.

4. TERMINATION
Either party may terminate this Agreement with [notice period] written notice.

5. CONFIDENTIALITY
Employee agrees to maintain confidentiality of proprietary information.

6. GOVERNING LAW
This Agreement shall be governed by the laws of [Jurisdiction]."""

        elif "affidavit" in prompt_lower:
            return """AFFIDAVIT

STATE OF [STATE]
COUNTY OF [COUNTY]

I, [Name], do solemnly declare and state that I am competent to make this Affidavit and that the facts stated herein are true and correct to the best of my knowledge, information, and belief.

[Insert statement of facts]

I declare under penalty of perjury under the laws of [State] that the foregoing is true and correct.

Executed on [Date] at [City], [State]

_________________________
[Declarant Name]
[Declarant Signature]

Subscribed and sworn to before me this ___ day of ________, 20___

_________________________
Notary Public"""

        elif "power of attorney" in prompt_lower:
            return """POWER OF ATTORNEY

KNOW ALL PERSONS BY THESE PRESENTS that I, [Principal Name], do hereby appoint [Agent Name] as my true and lawful attorney-in-fact.

The attorney-in-fact is authorized to:
- Manage all financial accounts
- Execute contracts on my behalf
- Handle real property transactions
- Collect debts
- Manage business interests

This Power of Attorney shall remain in effect until revoked by me in writing.

Executed on [Date]

_________________________
[Principal Name]

Witnessed and notarized this ___ day of ________, 20___

_________________________
Notary Public"""

        elif "question" in prompt_lower or "what" in prompt_lower:
            # General Q&A response
            return """Based on general legal principles and applicable law:

Key considerations include:
1. Parties' intentions and agreement terms
2. Applicable state and federal laws
3. Standard industry practices
4. Compliance requirements
5. Rights and obligations of all parties

For specific legal advice, please consult with a qualified attorney in your jurisdiction. This information is provided for educational purposes only and is not legal advice."""

        else:
            # Default response
            return """This is an AI-generated response based on legal knowledge and the information provided. 

Key Points:
- Review all terms carefully
- Ensure compliance with applicable laws
- Consider consulting with a legal professional
- Document all agreements in writing
- Keep records for future reference

Note: This response is generated by an AI system and should not be considered as legal advice."""

